document.addEventListener('DOMContentLoaded', () => {
    const textInput = document.getElementById('text-input');
    const summarizeBtn = document.getElementById('summarize-btn');
    const expandBtn = document.getElementById('expand-btn');
    const speakBtn = document.getElementById('speak-btn');
    const stopBtn = document.getElementById('stop-btn');
    const statusDiv = document.getElementById('status');
    const outputTextDiv = document.getElementById('output-text');

    summarizeBtn.addEventListener('click', () => {
        const text = textInput.value;
        if (text.trim() === '') {
            alert('Please enter some text.');
            return;
        }
        statusDiv.textContent = 'Summarizing...';
        // Placeholder for AI API call
        setTimeout(() => {
            const summary = "This is a placeholder summary. In a real application, this would be generated by an AI. " + text.substring(0, 100) + "...";
            outputTextDiv.textContent = summary;
            statusDiv.textContent = 'Summary complete.';
        }, 1000);
    });

    expandBtn.addEventListener('click', () => {
        const text = textInput.value;
        if (text.trim() === '') {
            alert('Please enter some text.');
            return;
        }
        statusDiv.textContent = 'Expanding...';
        // Placeholder for AI API call
        setTimeout(() => {
            const expansion = "This is a placeholder expansion. The original text was: '" + text + "'. In a real application, an AI would generate a more detailed version.";
            outputTextDiv.textContent = expansion;
            statusDiv.textContent = 'Expansion complete.';
        }, 1000);
    });

    speakBtn.addEventListener('click', () => {
        const text = outputTextDiv.textContent || textInput.value;
        if (text.trim() === '') {
            alert('Nothing to speak.');
            return;
        }
        const utterance = new SpeechSynthesisUtterance(text);
        speechSynthesis.speak(utterance);
        statusDiv.textContent = 'Speaking...';
        utterance.onend = () => {
            statusDiv.textContent = '';
        };
    });

    stopBtn.addEventListener('click', () => {
        speechSynthesis.cancel();
        statusDiv.textContent = '';
    });
});
